### ISSUE TITLE
Typing support

### ISSUE THREAD

**Issue by sobolevn** [Tishka17/dataclass_factory#25]
Hi! Thanks for the awesome project. 

It looks like you have covered almost all of your source code with type annotations, but currently it is not shipped to the final user.

I suggest to fix this situation. Here's how:
1. Create `py.typed` file in the root of the `dataclass_factory` folder, it is required for [PEP561](https://www.python.org/dev/peps/pep-0561/) to work. Example: https://github.com/dry-python/returns/blob/master/returns/py.typed
2. Change how public API is typed. Some method do miss return values. Some of them are missing generic parameters. Like this one: https://github.com/Tishka17/dataclass_factory/blob/master/dataclass_factory/factory.py#L80 It should be something like: `def load(self, data: Any, class_: Type[T]) -> T:` (do not forget about `Generic` base class)
3. Integrate `mypy` to check these annotations

This feature would improve developer experience and make this project even more awesome!

**Comment by Tishka17** [comment]
I did some changes in develop branch. 

1. I'm not sure how properly distribute `py.typed` file. 

2. Generic base class for factory not needed, because it is generics method wich returns different types based on args. But Schema is now generic

3. mypy shows problem with `is_type_var` method. I'm not sure if it false positive

**Comment by sobolevn** [comment]
I can help with a review if you open a new PR.
